# Extract polysemy information for the verbs
### This is what the synset info looks like in Wordnet

In [1]:
from nltk.corpus import wordnet as wn
import pandas as pd

# for POS (nouns)
wn.synsets('book', pos=wn.NOUN)

[Synset('book.n.01'),
 Synset('book.n.02'),
 Synset('record.n.05'),
 Synset('script.n.01'),
 Synset('ledger.n.01'),
 Synset('book.n.06'),
 Synset('book.n.07'),
 Synset('koran.n.01'),
 Synset('bible.n.01'),
 Synset('book.n.10'),
 Synset('book.n.11')]

In [2]:
# for POS (verbs)
wn.synsets('book', pos=wn.VERB)

[Synset('book.v.01'),
 Synset('reserve.v.04'),
 Synset('book.v.03'),
 Synset('book.v.04')]

In [3]:
# no POS
wn.synsets('book')

[Synset('book.n.01'),
 Synset('book.n.02'),
 Synset('record.n.05'),
 Synset('script.n.01'),
 Synset('ledger.n.01'),
 Synset('book.n.06'),
 Synset('book.n.07'),
 Synset('koran.n.01'),
 Synset('bible.n.01'),
 Synset('book.n.10'),
 Synset('book.n.11'),
 Synset('book.v.01'),
 Synset('reserve.v.04'),
 Synset('book.v.03'),
 Synset('book.v.04')]

# Example mini 'dataset'
### 'facorite' included to show how Wordnet deals with non-words (mispellings)

In [4]:
# import pandas as pd

# df = pd.DataFrame({'verb': ['have', 'jump', 'book', 'facorite']})
# df

In [5]:
# # calulate the number of verb synsets for each verb
# df['v_syn_count'] = df['verb'].apply(lambda x: len(wn.synsets(x, pos=wn.VERB)))
# # store the actual verb synsets for each verb
# df['v_synsets'] = df['verb'].apply(lambda x: [synset.name() for synset in wn.synsets(x, pos=wn.VERB)])
# # calculate the number of all synsets for each verb
# df['syn_count'] = df['verb'].apply(lambda x: len(wn.synsets(x)))
# # store the all synsets for each verb
# df['synsets'] = df['verb'].apply(lambda x: [synset.name() for synset in wn.synsets(x)])

# df

# Now run the code on the verb list

In [4]:
verb_count_df = pd.read_csv('verb_counts_27May.csv') 
verb_count_df

            verb  counts
0           have   70052
1           like   28565
2           play   21787
3           take   20375
4           wear   15695
...          ...     ...
3100      weenie       1
3101  depreciate       1
3102        dree       1
3103         pan       1
3104         ash       1

[3105 rows x 2 columns]

In [5]:
verb_count_df['verb']

0             have
1             like
2             play
3             take
4             wear
           ...
3100        weenie
3101    depreciate
3102          dree
3103           pan
3104           ash
Name: verb, Length: 3105, dtype: object

In [ ]:
# if any values in the df were 'NaN', remove (it will cause an error)
df = verb_count_df.dropna(subset=['verb'])
df

            verb  counts
0           have   70052
1           like   28565
2           play   21787
3           take   20375
4           wear   15695
...          ...     ...
3100      weenie       1
3101  depreciate       1
3102        dree       1
3103         pan       1
3104         ash       1

[3105 rows x 2 columns]

In [7]:
df = df.copy()

# calculate the number of verb synsets for each verb
df['v_syn_count'] = df['verb'].apply(lambda x: len(wn.synsets(x, pos=wn.VERB)))
# store the actual verb synsets for each verb
df['v_synsets'] = df['verb'].apply(lambda x: [synset.name() for synset in wn.synsets(x, pos=wn.VERB)])
# calculate the number of all synsets for each verb
df['syn_count'] = df['verb'].apply(lambda x: len(wn.synsets(x)))
# store the all synsets for each verb
df['synsets'] = df['verb'].apply(lambda x: [synset.name() for synset in wn.synsets(x)])

df.to_csv('synsets_27May.csv', index=False)
df

,verb,counts,v_syn_count,v_synsets,syn_count,synsets
0,have,70052,19,"[have.v.01, have.v.02, experience.v.03, own.v....",20,"[rich_person.n.01, have.v.01, have.v.02, exper..."
1,like,28565,5,"[wish.v.02, like.v.02, like.v.03, like.v.04, l...",11,"[like.n.01, like.n.02, wish.v.02, like.v.02, l..."
2,play,21787,35,"[play.v.01, play.v.02, play.v.03, act.v.03, pl...",52,"[play.n.01, play.n.02, play.n.03, maneuver.n.0..."
3,take,20375,42,"[take.v.01, take.v.02, lead.v.01, take.v.04, a...",44,"[return.n.06, take.n.02, take.v.01, take.v.02,..."
4,wear,15695,9,"[wear.v.01, wear.v.02, wear.v.03, wear.v.04, w...",12,"[wear.n.01, clothing.n.01, wear.n.03, wear.v.0..."
...,...,...,...,...,...,...
3100,weenie,1,0,[],1,[frank.n.02]
3101,depreciate,1,3,"[deprecate.v.02, depreciate.v.02, depreciate.v...",3,"[deprecate.v.02, depreciate.v.02, depreciate.v..."
3102,dree,1,0,[],0,[]
3103,pan,1,3,"[pan.v.01, pan.v.02, pan.v.03]",7,"[pan.n.01, pan.n.02, pan.n.03, pan.n.04, pan.v..."
3104,ash,1,1,[ash.v.01],4,"[ash.n.01, ash.n.02, ash.n.03, ash.v.01]"

In [8]:
# show all the rows where v_syn_count is 0
zero_v_synsets = df[df['v_syn_count'] == 0]
zero_v_synsets.to_csv('zero_v_synsets_27May.csv', index=False)
zero_v_synsets

,verb,counts,v_syn_count,v_synsets,syn_count,synsets
259,scuba,92,0,[],1,[aqualung.n.01]
293,sale,68,0,[],5,"[sale.n.01, sale.n.02, sale.n.03, sale.n.04, s..."
331,food,53,0,[],3,"[food.n.01, food.n.02, food.n.03]"
343,oppsite,48,0,[],0,[]
358,choice,43,0,[],5,"[choice.n.01, choice.n.02, option.n.02, choice..."
...,...,...,...,...,...,...
3094,starter,1,0,[],7,"[starter.n.01, starter.n.02, starter.n.03, new..."
3097,willgive,1,0,[],0,[]
3098,fatorite,1,0,[],0,[]
3100,weenie,1,0,[],1,[frank.n.02]
3102,dree,1,0,[],0,[]