## 1. Standardize spelling to American English 
## 2. Minimal spelling correction to account for possible typos (as described in the paper)

In [2]:
import pandas as pd

df = pd.read_csv('verb_noun_collocations_22May.csv')
efcam = df.dropna().copy()
efcam

,verb,v_xpos,noun,n_xpos,relation_type,sentence,cefr,learner_id,writing_id,topic,doc_index
0,brush,VB,tooth,NNS,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
1,wash,VB,face,NN,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
2,have,VB,breakfast,NN,obj,Have breakfast at nine thirty oclock.,A1,42261,2152,Introducing yourself by email,1
3,have,VBP,lunch,NN,obj,I have lunch at twenty oclock.,A1,42261,2152,Introducing yourself by email,1
4,have,VBP,lunch,NN,obj,"hi, My name is wendy, my favorite day is satur...",A1,19345,4126,Introducing yourself by email,2
...,...,...,...,...,...,...,...,...,...,...,...
405215,have,VBP,lunch,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405216,hikingwith,VBG,brother,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405217,have,VBP,breakfast,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405218,go,VBP,reatuerount,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405219,like,VBP,sunning,NN,obj,"I like sunning,",C1,127795,558749,Writing an article about a superstore,106976

In [3]:
from breame.spelling import british_spelling_exists, get_american_spelling

def standardize_word_to_american(word):
    """
    Convert a British English word to American English.
    Checks if the word is British English, then converts if it is.
    """
    if word is None or pd.isna(word):
        return word
        
    # Check if this word is recognized as British English
    if british_spelling_exists(word):
        # Convert to American spelling
        return get_american_spelling(word)
    else:
        # Keep the original word if it's not recognized as British
        return word

# Apply function to the 'verb' and 'noun' columns in EFCAMDAT
efcam.loc[:, 'verb'] = efcam['verb'].apply(standardize_word_to_american)
efcam.loc[:, 'noun'] = efcam['noun'].apply(standardize_word_to_american)
efcam

,verb,v_xpos,noun,n_xpos,relation_type,sentence,cefr,learner_id,writing_id,topic,doc_index
0,brush,VB,tooth,NNS,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
1,wash,VB,face,NN,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
2,have,VB,breakfast,NN,obj,Have breakfast at nine thirty oclock.,A1,42261,2152,Introducing yourself by email,1
3,have,VBP,lunch,NN,obj,I have lunch at twenty oclock.,A1,42261,2152,Introducing yourself by email,1
4,have,VBP,lunch,NN,obj,"hi, My name is wendy, my favorite day is satur...",A1,19345,4126,Introducing yourself by email,2
...,...,...,...,...,...,...,...,...,...,...,...
405215,have,VBP,lunch,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405216,hikingwith,VBG,brother,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405217,have,VBP,breakfast,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405218,go,VBP,reatuerount,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405219,like,VBP,sunning,NN,obj,"I like sunning,",C1,127795,558749,Writing an article about a superstore,106976

# Prepare proper nouns from Paul Nation's list
### this will reduce the chance of words being corrected as proper nouns (previous attempt included corrections such as adam and belfast)
#### Nation, I.S.P. (2017). The BNC/COCA Level 6 word family lists (Version 1.0.0) [Data file]. Available from http://www.victoria.ac.nz/lals/staff/paul-nation.aspx

In [4]:
# read the txt file basewrd31_proper_nouns.txt and print the contents
# remove tabs and lowercase the contents
# add each line to an item # in a list called proper_nouns
file_path = 'basewrd31_proper_nouns.txt'

with open(file_path, 'r') as file:
    contents = file.read()
    contents = contents.replace('\t', '').lower()
    proper_nouns = contents.splitlines()
    proper_nouns_set = set(proper_nouns)  # Convert to a set to potentially speed up lookups

# print the first 100 proper nouns
proper_nouns_set

{'bachan',
 'timaru',
 'bert',
 'birkin',
 'ohio',
 'sejm',
 'knopf',
 'indonesian',
 'rafiq',
 'hillhouse',
 'berkshire',
 'hadlee',
 'tanneke',
 'eldorado',
 'ontario',
 'benadryl',
 'mab',
 'imbert',
 'rossignol',
 'hindu',
 'gorbachev',
 'nai',
 'saaid',
 'devraux',
 'cusack',
 'mccall',
 'thurman',
 'gulliver',
 'magdalen',
 'amalee',
 'bergman',
 'nikau',
 'lunamaria',
 'inverclyde',
 'tonnay',
 'hoffmann',
 'bagh',
 'ennals',
 'jose',
 'izvestiya',
 'posidonius',
 'chavez',
 'rundi',
 'bcci',
 'margarets',
 'tannadice',
 'whitton',
 'pilkington',
 'silverado',
 'sharad',
 'marcello',
 'stein',
 'arguello',
 'lokpal',
 'americanisms',
 'talman',
 'claxton',
 'sabina',
 'goodier',
 'totowa',
 'sfa',
 'ena',
 'coleridge',
 'maxine',
 'norwood',
 'mcwhirter',
 'roswell',
 'vieux',
 'nader',
 'carnarvon',
 'sienna',
 'massport',
 'malagasy',
 'raul',
 'schutz',
 'crus',
 'nielson',
 'krishan',
 'giulio',
 'tigris',
 'zaragoza',
 'prebble',
 'karpoori',
 'felton',
 'andreotti',
 'phillipson',
 'borland',
 'gillis',
 'kidd',
 'araminta',
 'apaches',
 'australian',
 'shatford',
 'mckillop',
 'farhady',
 'jutland',
 'khushoo',
 'shuttleworth',
 'paviour',
 'senegal',
 'halpingham',
 'hauxwell',
 'ripley',
 'mcilroy',
 'inglis',
 'rosyth',
 'lerwick',
 'weardale',
 'malum',
 'kirov',
 'putnam',
 'loring',
 'brasch',
 'galovitch',
 'sharwood',
 'welshman',
 'sikh',
 'camilla',
 'schick',
 'nichol',
 'harley',
 'mihal',
 'jh',
 'ocd',
 'stalinofskivitchdavitovichski',
 'gozo',
 'karajan',
 'seifert',
 'barre',
 'timmins',
 'tripathi',
 'curzon',
 'constantinople',
 'mathias',
 'culley',
 'hooten',
 'scotrail',
 'gandhiji',
 'husrev',
 'maramarua',
 'bethlehem',
 'morelli',
 'haakon',
 'tarun',
 'freya',
 's2',
 'dutchman',
 'irb',
 'palmers',
 'snellville',
 'trigg',
 'bonetti',
 'hollywood',
 'ngc',
 'hundy',
 'jens',
 'mcardle',
 'welshing',
 'schwartzes',
 'thorpe',
 'oban',
 'shotton',
 'penistone',
 'simba',
 'chazzer',
 'moorgate',
 'tosca',
 'monie',
 'brisbane',
 'rattray',
 'fairlane',
 'kleinwort',
 'harmondsworth',
 'barrie',
 'dail',
 'berich',
 'thackeray',
 'madra',
 'doh',
 'wooster',
 'le',
 'visigoths',
 'stoli',
 'asm',
 'sgurr',
 'guangzhou',
 'marquand',
 'scotsport',
 'tonkin',
 'gaspar',
 'wis',
 'fridolanna',
 'pacey',
 'indus',
 'radnor',
 'symonds',
 'robb',
 'silymarin',
 'stc',
 'rosenblatt',
 'dann',
 'andika',
 'b2',
 'bala',
 'durand',
 'rotorua',
 'athos',
 'capaldi',
 'murf',
 'bronte',
 'bhagwat',
 'linares',
 'belka',
 'miramar',
 'mera',
 'felix',
 'shepton',
 'rousseau',
 'tumin',
 'woodforde',
 'mesa',
 'petropavlovsk',
 'zoolander',
 'arthur',
 'morocco',
 'dreyfus',
 'everington',
 'squidgy',
 'boudreaux',
 'deryck',
 'fricker',
 'sullart',
 'pina',
 'wolfson',
 'trivers',
 'dibben',
 'tootall',
 'ellie',
 'luigi',
 'bitterbuck',
 'salvadorian',
 'redenbacher',
 'b6',
 'sqn',
 'obama',
 'hitchcock',
 'seko',
 'timothy',
 'hislop',
 'wagha',
 'gian',
 'jesus',
 'jauncey',
 'marcelo',
 'prytania',
 'halabi',
 'bott',
 'zadora',
 'mckenna',
 'ecr',
 'bettelheim',
 'vieng',
 'jameson',
 'radley',
 'kirpal',
 'bathgate',
 'kerstin',
 'nuffield',
 'ra',
 'patricia',
 'southland',
 'newyork',
 'winthrop',
 'highgate',
 'patusan',
 'nilp',
 'aiadmk',
 'dallas',
 'gibb',
 'tummel',
 'rockford',
 'mulholland',
 'yenbo',
 'bossman',
 'gwendolyn',
 'lesus',
 'stamford',
 'murren',
 'spurzheim',
 'iowa',
 'pontillo',
 'duisburg',
 'kremlin',
 'hogwarts',
 'sloane',
 'delacroixs',
 'ã†thelred',
 'tibetans',
 'muskegon',
 'bnfl',
 'magwitch',
 'mcconville',
 'chester',
 'maryport',
 'warton',
 'brahmachari',
 'memphis',
 'anwar',
 'hauptmann',
 'lehotay',
 'elvis',
 'fbi',
 'mcguinness',
 'beverly',
 'haver',
 'mcalpine',
 'stengel',
 'carnera',
 'aljaafreh',
 'bughes',
 'angalo',
 'cassell',
 'clary',
 'eleusis',
 'eggleton',
 'fp',
 'pattaya',
 'benvinguts',
 'bocce',
 'munn',
 'freddy',
 'idc',
 'brownings',
 'bretherick',
 'singleton',
 'tallendorf',
 'clitheroe',
 'maltese',
 'doherty',
 'quixote',
 'deshmukh',
 'bjp',
 'crissy',
 'ames',
 'belgians',
 'trippier',
 'normie',
 'sann',
 'ymca',
 'toestill',
 'malaya',
 'knossos',
 'whitcombe',
 'donaghy',
 'herron',
 'beame',
 'montero',
 'muirhead',
 'khieu',
 'aldington',
 'tralee',
 'parichy',
 'maharet',
 'hermosa',
 'cumstein',
 'christoph',
 'papua',
 'bldg',
 'terrebonne',
 'nirmala',
 'morrison',
 'bercovicz',
 'llangollen',
 'jennifer',
 'tremont',
 'navratilova',
 'pennine',
 'chongs',
 'oregon',
 'ballstein',
 'rylie',
 'southam',
 'bulgari',
 'gribbons',
 'zwilling',
 'maplecrest',
 'steele',
 'kamaji',
 'krispy',
 'millie',
 'kassem',
 'yavar',
 'wyse',
 'heathcoat',
 'jap',
 'spence',
 'hukilau',
 'feltrim',
 'basten',
 'galvone',
 'tubman',
 'lonny',
 'aaronson',
 'tashkent',
 'kang',
 'jacobeans',
 'klondyke',
 'magirk',
 'liberian',
 'drinkhouse',
 'ilyushin',
 'schlãƒ',
 'spr',
 'ulthuan',
 'blondel',
 'skoda',
 'jonno',
 'bensonhurst',
 'dodd',
 'bismarck',
 'marx',
 'saturn',
 'jorge',
 'newley',
 'darren',
 'tappin',
 'roschmann',
 'fo',
 'paines',
 'lainie',
 'crombie',
 'chunovic',
 'hur',
 'lofgren',
 'wordsworth',
 'dafydd',
 'pressley',
 'linley',
 'lamar',
 'jezreel',
 'dorman',
 'hurst',
 'joni',
 'zener',
 'molvedo',
 'semitic',
 'carlow',
 'citrine',
 'lochalsh',
 'pollard',
 'tintagel',
 'schnurson',
 'renaldo',
 'gorm',
 'hugo',
 'helene',
 'johnvonneumann',
 'autonomen',
 'widgery',
 'middlesbrough',
 'lugosi',
 'sonji',
 'carinii',
 'friegas',
 'calton',
 'clevedon',
 'spain',
 'salinger',
 'croce',
 'kirgiz',
 'nyu',
 'skadar',
 'zoloft',
 'ukraine',
 'padfoot',
 'roseberry',
 'stacey',
 'jamie',
 'greenwood',
 'alberts',
 'qaeda',
 'geri',
 'pontypridd',
 'seri',
 'royston',
 'blackrock',
 'sinfield',
 'cowpe',
 'wastell',
 'zuwanie',
 'pekos',
 'runneth',
 'mangaroa',
 'yorke',
 'aran',
 'leica',
 'fothergill',
 'portobello',
 'inisfree',
 'elroy',
 'hodge',
 'garston',
 'florenz',
 'dersingham',
 'rafiullah',
 'tavistock',
 'bellwood',
 'leona',
 'sicilia',
 'hibs',
 'pellegrino',
 'cornwall',
 'mizell',
 'bahadur',
 'libyan',
 'hendry',
 'delia',
 'waldorf',
 'celts',
 'gillian',
 'nagaland',
 'rockies',
 'ono',
 'shaposhnikov',
 'nagayalanka',
 'frisby',
 'plummer',
 'bomberg',
 'silvio',
 'feng',
 'lumple',
 'cotty',
 'quinta',
 'serebryakov',
 'garnier',
 'johanne',
 'laos',
 'liefers',
 'parmelee',
 'thaddeus',
 'griswalds',
 'rangaswami',
 'forsyth',
 'nio',
 'afghans',
 'macgill',
 'yueh',
 'nofziger',
 'coase',
 'hoak',
 'tuttle',
 'danes',
 'segal',
 'orlov',
 'notting',
 'baraclough',
 'seveso',
 'bernese',
 'eb',
 'ltte',
 'cambodians',
 'humberto',
 'gantt',
 'macquillan',
 'pyrie',
 'kobe',
 'porlock',
 'kepler',
 'uefa',
 'eduardo',
 'gustavo',
 'bickerstaffe',
 'shia',
 'tretyakov',
 'ragd',
 'latif',
 'cumming',
 'darkfall',
 'nimmo',
 'cesario',
 'roberta',
 'mccrory',
 'summerson',
 'butterbean',
 'thu',
 'blois',
 'hoffa',
 'monaghan',
 'lizzie',
 'vanderhoff',
 'los',
 'rabscuttle',
 'kerrey',
 'louisa',
 'julius',
 'lamberto',
 'leicester',
 'cb',
 'mainwaring',
 'linton',
 'alt',
 'zellner',
 'mirawdeli',
 'stace',
 'albright',
 'liffe',
 'benesch',
 'rayne',
 'delhomme',
 'laughlin',
 'hatcher',
 'capern',
 'gelson',
 'vidyarthi',
 'moudy',
 'pilato',
 'ramanathapuram',
 'manilow',
 'albany',
 'psd',
 'mcnuggets',
 'mebbe',
 'dorr',
 'schuyler',
 'rhondda',
 'clwyd',
 'nischwitz',
 'verdun',
 'cgi',
 'deptford',
 'llar',
 'wingate',
 'catlins',
 'southgate',
 'marinello',
 'apollonians',
 'andy',
 'merritsville',
 'mcnaught',
 'denholm',
 'tatham',
 'a38',
 'swinstead',
 'vi',
 'deauville',
 'canseco',
 'deadwood',
 'sampras',
 'saa',
 'kotagiri',
 'bonard',
 'genesee',
 'ilchester',
 'hollenbeck',
 'irena',
 'nicaea',
 'pitts',
 'midatlantic',
 'haydn',
 'nuprin',
 'grugman',
 'heli',
 'hã‰loise',
 'hyer',
 'korn',
 'limpar',
 'scrapiron',
 'sunbury',
 'decker',
 'phetam',
 'smalley',
 'bergin',
 'goldwyn',
 'shampanskoe',
 'heil',
 'lindy',
 'rocester',
 'harry',
 'eiger',
 'adamec',
 'elwyn',
 'brompton',
 'knin',
 'mccardle',
 'ribblehead',
 'woolf',
 'richardson',
 'opie',
 'avila',
 'rioch',
 'dunne',
 'alyson',
 'bessey',
 'l4',
 'russa',
 'nucker',
 'clouston',
 'gillan',
 'cck',
 'matka',
 'dredd',
 'daniel',
 'cocteau',
 'corinthians',
 'azt',
 'robby',
 'everglot',
 'tchotchke',
 'wedderburn',
 'roseland',
 'viyella',
 'aztec',
 'samoans',
 'phu',
 'putney',
 'baberton',
 'cardus',
 'ripa',
 'ccw',
 'becker',
 'hindle',
 'oppenheimer',
 'berman',
 'arroll',
 'hasselhoff',
 'lehrer',
 'mesopotamia',
 'hignett',
 'lanergan',
 'robathan',
 'mourne',
 'sarin',
 'heidelberg',
 'muirfield',
 'verona',
 'tuc',
 'sheringham',
 'madigan',
 'k2',
 'ansley',
 'munros',
 'uphall',
 'quincy',
 'enos',
 'crampton',
 'manjula',
 'brownstone',
 'mctarry',
 'letterman',
 'morgan',
 'gandak',
 'caird',
 'jorda',
 'hera',
 'paganini',
 'sulley',
 'srs',
 'warne',
 'abilene',
 'dalglish',
 'strickland',
 'wigglesworth',
 'shabbat',
 'mediterranean',
 'antonia',
 'mchale',
 'pickering',
 'trichy',
 'wolvercote',
 'absolut',
 'joshua',
 'daiena',
 'lazar',
 'siad',
 'dunstable',
 'scorton',
 'mullan',
 'clairol',
 'ironside',
 'evian',
 'mason',
 'rawson',
 'mackeson',
 'ridgeway',
 'disimone',
 'novotny',
 'weathercock',
 'jayapuram',
 'stanger',
 'mittal',
 'poyntz',
 'ritz',
 'watney',
 'nvocc',
 'angelini',
 'nahal',
 'thach',
 'washinton',
 'slymington',
 'laad',
 'hofmann',
 'welch',
 'sheneequa',
 'aderman',
 'roseman',
 'fiske',
 'barrymore',
 'bagbay',
 'germania',
 'poncenby',
 'sellars',
 'beith',
 'omani',
 'belur',
 'impey',
 'southend',
 'mixner',
 'arte',
 'polos',
 'benstede',
 'hargrave',
 'delius',
 'dimaggio',
 'mccready',
 'gorton',
 'wulfhere',
 'maff',
 'fayeds',
 'bing',
 'joseph',
 'reata',
 'hamble',
 'lanning',
 'wenlock',
 'radulfus',
 'wmc',
 'rosburg',
 'sabena',
 'offa',
 'darley',
 'hellstrom',
 'quiss',
 'brabham',
 'salvy',
 'camborne',
 'modrow',
 'ahab',
 'farringdon',
 'heselton',
 'wim',
 'brentano',
 'irc',
 'reddings',
 'nec',
 'carlsons',
 'samana',
 'parvis',
 'falk',
 'rowell',
 'horley',
 'hyde',
 'alger',
 'stott',
 'hinderclay',
 'connaught',
 'harrogate',
 'peggotty',
 'mgadzah',
 'dulux',
 'huxley',
 'hasler',
 'topliss',
 'gumbert',
 'rushmore',
 'merrill',
 'trafford',
 'caldecott',
 'etta',
 'merseyside',
 'wragbys',
 'ivanov',
 'edward',
 'dennis',
 'shenzi',
 'belanger',
 'feldman',
 'pocklington',
 'brundle',
 'tyburn',
 'flodden',
 'garraway',
 'broek',
 'linnaeus',
 'carovei',
 'abdulkerim',
 'e1',
 'kraus',
 'cipriani',
 'shogun',
 'picts',
 'napper',
 'yankovic',
 'katinka',
 'novick',
 'tammuz',
 'lanier',
 'ligier',
 'vartan',
 'lazarus',
 'galicia',
 'hove',
 'charlayne',
 'trekkie',
 'pims',
 'pirelli',
 'manohar',
 'fratelli',
 'keke',
 'drebin',
 'searles',
 'mutney',
 'kishore',
 'porto',
 'estonian',
 'patrick',
 'heisenberg',
 'wyllie',
 'daventry',
 'vogel',
 'yang',
 'aeneid',
 'cunninghame',
 'rhs',
 'juneja',
 'stedeford',
 'sopers',
 'gerona',
 'pickfords',
 'languedoc',
 'capcom',
 'klerk',
 'coahr',
 'cookstown',
 'ramaphosa',
 'simonelli',
 'nicosia',
 'wilbur',
 'popplewell',
 'vallance',
 'lesean',
 'wainford',
 'jannie',
 'cronin',
 'gemmill',
 'whitechapel',
 'koenig',
 'pumilia',
 'guil',
 'hardcastle',
 'rca',
 'francia',
 'chagall',
 'copley',
 'indira',
 'vail',
 'foggies',
 'livingstone',
 'patnaik',
 'lorri',
 'tibbs',
 'mindy',
 'ellison',
 'urdu',
 'norrington',
 'ryuian',
 'massachusetts',
 'hathaway',
 'cavers',
 'waikare',
 'pacy',
 'ctl',
 'ajmer',
 'paswan',
 'birgit',
 'aquila',
 'laibon',
 'mandalay',
 'tilbury',
 'sanka',
 'gretzky',
 'planktopolis',
 'yorath',
 'dabeerpura',
 'vinelott',
 'millwall',
 'margery',
 'stewarts',
 'fidel',
 'bolognese',
 'christchurch',
 ...}

## Using pyspellcheck to identify misspellings and suggest candidates (Edit Distance / Levensthein Distance <=2)
### Use Wordnet to only offer corrections in same POS
### Also choose candidates based on frequency (New-GSL (Gablasova & Brezina, 2015), then wordfreq package)
### Also don't correct to proper noun
### Some manual corrections & words not to be corrected are dealt with at the start of this block

In [5]:
import re
import string
import pandas as pd
from collections import defaultdict
from spellchecker import SpellChecker
from nltk.corpus import wordnet as wn
from wordfreq import zipf_frequency

# -----------------------------------------------
# Manual validation and correction
# -----------------------------------------------

# Checked all 'mispelled verbs' with frequency >= 2
# 'e-mail' was the only one that I could find
valid_verbs = ['e-mail']

# Manually correct nouns in df['noun']
# 'tvs' and 'cds' were clearly not lemmatized properly (maybe due to lowercasing?)
manual_noun_corrections = {
    'tv.': 'tv',
    'tvs': 'tv',
    'cd.': 'cd',
    'cds': 'cd',
}

# Manual corrections for verbs
manual_verb_corrections = {
    'paly': 'play'
}

# Checked all misspelled nouns with frequency >= 2
# 'rmb' is currency, always preceded by a number (maybe not in BNC, but kept anyway)
# Some of these words are likely not in the dictionary because they are recent
# They will also not be in the BNC, but we might flag them manually as acceptable
# 'etc.' et cetera is classified as a noun in some dictionaries, e.g. Oxford Learner's Dictionary
valid_nouns = [
    'tv', 'e-mail', 'mp3', 'etc.', 'non-stop', 'e-ticket', 'smartphone', 'unsatisfaction',
    'cv', 'rmb', 'mba', 'pc', 'ceo', 'fiance', 'dvd', 'mini-skirt', 'bbq', 'e-book',
    'wifi', 'app', 'toefl', 'ef', 'mooncake', 'a.m.', 'p.m.', 'cbt', 'mangoe', 'backsplash',
    'etc.', 'cctv', 'diy', 
]

# -----------------------------------------------
# Double-check lowercasing and stripping
# -----------------------------------------------

# Normalize case and strip whitespace
efcam['verb'] = efcam['verb'].str.lower().str.strip()
efcam['noun'] = efcam['noun'].str.lower().str.strip()

# -----------------------------------------------
# Build Wordnet vocabulary sets
# -----------------------------------------------

# Extract all lemma names for nouns and verbs
wordnet_nouns = {lemma.name().lower() for syn in wn.all_synsets('n') for lemma in syn.lemmas()}
wordnet_verbs = {lemma.name().lower() for syn in wn.all_synsets('v') for lemma in syn.lemmas()}

# Combine with manually validated words
noun_vocab = wordnet_nouns.union(valid_nouns)
verb_vocab = wordnet_verbs.union(valid_verbs)


spell_noun = SpellChecker(distance=2)
spell_noun.word_frequency.load_words(noun_vocab)

spell_verb = SpellChecker(distance=2)
spell_verb.word_frequency.load_words(verb_vocab)

# -----------------------------------------------
# Load NGSL lists for high frequency candidates
# -----------------------------------------------

ngsl_df = pd.read_csv("NewGSL_ame.csv")

# Lowercase headwords just in case
ngsl_df['Headword'] = ngsl_df['Headword'].str.lower()

# Filter by part of speech
ngsl_nouns = ngsl_df[ngsl_df['pos'] == 'n']
ngsl_verbs = ngsl_df[ngsl_df['pos'] == 'v']

# Build rank dictionaries
ngsl_noun_rank = dict(zip(ngsl_nouns['Headword'], ngsl_nouns['Rank']))
ngsl_verb_rank = dict(zip(ngsl_verbs['Headword'], ngsl_verbs['Rank']))


# -----------------------------------------------
# Spell-correct a single token with overrides
# -----------------------------------------------

def sanitize_word(word):
    # Remove leading/trailing punctuation and stray non-word characters
    word = word.strip().lower()
    word = re.sub(r"^[^a-zA-Z]+", "", word)  # leading non-letters
    word = re.sub(r"[^a-zA-Z]+$", "", word)  # trailing non-letters
    word = word.replace("'", "")  # remove inner apostrophes
    return word

def correct_token(word, wordnet_vocab, valid_list, correction_dict, spellchecker, pos_tag, proper_nouns):
    if not isinstance(word, str):
        return word

    raw_word = word
    word = sanitize_word(word)
    if word == "":
        return raw_word

    word = correction_dict.get(word, word)

    # Skip correction if it's a proper noun
    if word in proper_nouns:
        return raw_word

    if word in valid_list or (word in wordnet_vocab and word not in proper_nouns):
        return word

    candidates = spellchecker.candidates(word)
    if candidates:
        valid_cands = [cand for cand in candidates if cand in wordnet_vocab and cand not in proper_nouns]
        if valid_cands:
            # use NGSL highest rank words first, if not in NGSL, use Zipf frequency
            # Define rank source
            ngsl_rank = ngsl_noun_rank if pos_tag == 'n' else ngsl_verb_rank

            def score(w):
                return (
                    -ngsl_rank.get(w, float('inf')),  # NGSL rank: lower is better
                    zipf_frequency(w, "en", wordlist="best")  # Zipf frequency as tie-breaker
                )

            return max(valid_cands, key=score)

    return raw_word


# -----------------------------------------------
# Correct verb-noun collocation pair
# -----------------------------------------------

def correct_collocation_spellchecker(verb, noun):
    original_verb = verb
    original_noun = noun

    corrected_verb = correct_token(
    verb,
    wordnet_verbs,
    valid_verbs,
    manual_verb_corrections,
    spell_verb,
    'v',
    proper_nouns_set
)

    corrected_noun = correct_token(
    noun,
    wordnet_nouns,
    valid_nouns,
    manual_noun_corrections,
    spell_noun,
    'n',
    proper_nouns_set
)

    was_corrected = (corrected_verb != verb or corrected_noun != noun)
    return corrected_verb, (verb if corrected_verb != verb else "-"), corrected_noun, (noun if corrected_noun != noun else "-"), was_corrected

# -----------------------------------------------
# Apply corrections to learner corpus
# -----------------------------------------------

corrections = efcam.apply(
    lambda row: correct_collocation_spellchecker(row['verb'], row['noun']),
    axis=1,
    result_type='expand'
)

# Rename for clarity
corrections.columns = ['corrected_verb', 'original_verb', 'corrected_noun', 'original_noun', '_was_corrected']

# Replace original verb/noun with corrected versions
efcam['verb'] = corrections['corrected_verb']
efcam['noun'] = corrections['corrected_noun']

# Insert original_verb after 'verb'
verb_index = efcam.columns.get_loc('verb')
efcam.insert(verb_index + 1, 'original_verb', corrections['original_verb'])

# Insert original_noun after 'noun'
noun_index = efcam.columns.get_loc('noun')
efcam.insert(noun_index + 1, 'original_noun', corrections['original_noun'])
efcam

,verb,original_verb,v_xpos,noun,original_noun,n_xpos,relation_type,sentence,cefr,learner_id,writing_id,topic,doc_index
0,brush,-,VB,tooth,-,NNS,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
1,wash,-,VB,face,-,NN,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
2,have,-,VB,breakfast,-,NN,obj,Have breakfast at nine thirty oclock.,A1,42261,2152,Introducing yourself by email,1
3,have,-,VBP,lunch,-,NN,obj,I have lunch at twenty oclock.,A1,42261,2152,Introducing yourself by email,1
4,have,-,VBP,lunch,-,NN,obj,"hi, My name is wendy, my favorite day is satur...",A1,19345,4126,Introducing yourself by email,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
405215,have,-,VBP,lunch,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405216,hikingwith,-,VBG,brother,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405217,have,-,VBP,breakfast,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405218,go,-,VBP,reatuerount,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405219,like,-,VBP,sunning,-,NN,obj,"I like sunning,",C1,127795,558749,Writing an article about a superstore,106976

# Standardize to American spellings again
### Wornet might also contain British spellings

In [10]:
# Apply function to the 'verb' and 'noun' columns in EFCAMDAT
efcam.loc[:, 'verb'] = efcam['verb'].apply(standardize_word_to_american)
efcam.loc[:, 'noun'] = efcam['noun'].apply(standardize_word_to_american)
efcam

,verb,original_verb,v_xpos,noun,original_noun,n_xpos,relation_type,sentence,cefr,learner_id,writing_id,topic,doc_index
0,brush,-,VB,tooth,-,NNS,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
1,wash,-,VB,face,-,NN,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
2,have,-,VB,breakfast,-,NN,obj,Have breakfast at nine thirty oclock.,A1,42261,2152,Introducing yourself by email,1
3,have,-,VBP,lunch,-,NN,obj,I have lunch at twenty oclock.,A1,42261,2152,Introducing yourself by email,1
4,have,-,VBP,lunch,-,NN,obj,"hi, My name is wendy, my favorite day is satur...",A1,19345,4126,Introducing yourself by email,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
405215,have,-,VBP,lunch,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405216,hikingwith,-,VBG,brother,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405217,have,-,VBP,breakfast,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405218,go,-,VBP,reatuerount,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405219,like,-,VBP,sunning,-,NN,obj,"I like sunning,",C1,127795,558749,Writing an article about a superstore,106976

# check if British spellings still exist

In [11]:
# if british_spelling_exists in efcam['verb'] and efcam['noun'], print the words
for word in efcam['verb']:
    if british_spelling_exists(word):
        print(word)

In [12]:
# if british_spelling_exists in efcam['verb'] and efcam['noun'], print the words
for word in efcam['noun']:
    if british_spelling_exists(word):
        print(word)

In [ ]:
# efcam.to_csv('verb_noun_collocations_27May.csv', index=False)
efcam

,verb,original_verb,v_xpos,noun,original_noun,n_xpos,relation_type,sentence,cefr,learner_id,writing_id,topic,doc_index
0,brush,-,VB,tooth,-,NNS,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
1,wash,-,VB,face,-,NN,obj,Then brush my teeth and wash my face.,A1,42261,2152,Introducing yourself by email,1
2,have,-,VB,breakfast,-,NN,obj,Have breakfast at nine thirty oclock.,A1,42261,2152,Introducing yourself by email,1
3,have,-,VBP,lunch,-,NN,obj,I have lunch at twenty oclock.,A1,42261,2152,Introducing yourself by email,1
4,have,-,VBP,lunch,-,NN,obj,"hi, My name is wendy, my favorite day is satur...",A1,19345,4126,Introducing yourself by email,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
405215,have,-,VBP,lunch,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405216,hikingwith,-,VBG,brother,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405217,have,-,VBP,breakfast,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405218,go,-,VBP,reatuerount,-,NN,obj,"I have lunch at 12 o'clock, In the afternoon, ...",C1,127795,558749,Writing an article about a superstore,106976
405219,like,-,VBP,sunning,-,NN,obj,"I like sunning,",C1,127795,558749,Writing an article about a superstore,106976

In [14]:
# Extract verb-noun pairs for counting
verb_noun_pairs = efcam.groupby(by=['verb', 'noun']).size().reset_index(name='count')
coocurence_frequency_df = verb_noun_pairs.sort_values(by='count', ascending=False)
coocurence_frequency_df.to_csv('coocurrence_frequency_27May.csv', index=False)
coocurence_frequency_df

          verb     noun  count
20285     have     hair   5904
26986     like      job   5285
50201    watch       tv   3678
20074     have      eye   3627
34562     play     game   3581
...        ...      ...    ...
10     abandon     work      1
9      abandon      way      1
8      abandon  poverty      1
7      abandon    major      1
6      abandon    habit      1

[51601 rows x 3 columns]

In [15]:
# Extract value counts of all_collocations_df["verb"] to a df
verb_counts_df = efcam['verb'].value_counts().reset_index(name='counts')
verb_counts_df.to_csv('verb_counts_27May.csv', index=False)
verb_counts_df

            verb  counts
0           have   70052
1           like   28565
2           play   21787
3           take   20375
4           wear   15695
...          ...     ...
3100      weenie       1
3101  depreciate       1
3102        dree       1
3103         pan       1
3104         ash       1

[3105 rows x 2 columns]